[package]
name = "rustyplot-render"
description = "wgpu rendering backend for rustyplot"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rustyplot-core.workspace = true
wgpu.workspace = true
bytemuck.workspace = true
log.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
wgpu = { workspace = true, features = ["webgl"] }
